spring:
  application:
    name: transaction-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
server:
  port: 8080
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka